[package]
name = "refineid-unix-pkcs11"
description = "PKCS#11 v2.40 cdylib module for FINEID (wrapping refineid-core)."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[features]
default = []
pin-change = ["refineid-pkcs11/pin-change"]
test-pin-env = ["refineid-pkcs11/test-pin-env"]

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]
name = "refineid_pkcs11"

[dependencies]
refineid-pkcs11.workspace = true

[dev-dependencies]
refineid-lib-core.workspace = true
libc = "0.2"
